version: "3.8"

services:

  #
  # xion-mainnet-1
  #

  gentx:
    image: burntnetwork/xion:0.3.7
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/gentx.sh
    environment:
      MONIKER: "Helios Staking"
      CHAIN_ID: "xion-mainnet-1"
      GENESIS_AMOUNT: "1000000uxion"
      KEYNAME: "heliosstaking.com"
      KEYRING_BACKEND: "file"
      KEYRING_PASSPHRASE: "SuperSecretPassphrase42069"
      MNEMONIC: ""  # giant dynamic salmon...
      VAL_COMMISSION_MAX_RATE: "1.00"
      VAL_COMMISSION_MAX_CHANGE_RATE: "1.00"
      VAL_COMMISSION_RATE: "1.00"
      VAL_DETAILS: "https://heliosstatking.com"
      VAL_IDENTITY: "-"
      VAL_SECURITY_CONTACT: "kevin@heliosstatking.com"
      VAL_WEBSITE: "https://heliosstatking.com"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-mainnet-1:/tmp/testnet

  add-genesis-account:
    image: burntnetwork/xion:0.3.7
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/add-genesis-account.sh
    environment:
      MONIKER: "Helios Staking"
      CHAIN_ID: "xion-mainnet-1"
      GENESIS_AMOUNT: "1000000uxion"
      ADDRESS: ""
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-mainnet-1:/tmp/testnet

  collect-gentxs:
    image: burntnetwork/xion:0.3.7
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/collect-gentxs.sh
    environment:
      MONIKER: "Helios Staking"
      CHAIN_ID: "xion-mainnet-1"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-mainnet-1:/tmp/testnet

  validate-genesis:
    image: burntnetwork/xion:0.3.7
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/validate-genesis.sh
    environment:
      MONIKER: "Helios Staking"
      CHAIN_ID: "xion-mainnet-1"
    volumes:
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-mainnet-1:/tmp/testnet

  generate-hashes:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/generate-hashes.sh
    volumes:
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-mainnet-1:/tmp/testnet

  verify-hashes:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    command:
      - /tmp/scripts/verify-hashes.sh
    volumes:
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-mainnet-1:/tmp/testnet

  #
  # xion-testnet-1
  #

  validate-genesis-xion-testnet-1:
    image: burntnetwork/xion:0.1.0
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/validate-genesis.sh
    environment:
      MONIKER: "Helios Staking"
      CHAIN_ID: "xion-testnet-1"
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-testnet-1:/tmp/testnet

  generate-hashes-xion-testnet-1:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/generate-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-testnet-1:/tmp/testnet

  verify-hashes-xion-testnet-1:
    image: debian:bookworm-20240130-slim
    platform: linux/amd64
    user: xiond:xiond
    command:
      - /tmp/scripts/verify-hashes.sh
    volumes:
      - ./.docker/home:/home/xiond/.xiond
      - ./.docker/scripts:/tmp/scripts
      - ./mainnet/xion-testnet-1:/tmp/testnet
